// Generated by CoffeeScript 1.4.0

define(function() {
  var rclass, trim;
  rclass = /[\t\r\n]/g;
  trim = function(s) {
    return s && s.replace(/^\s+|\s+$/g, '');
  };
  return {
    addClass: function(element, className) {
      var cur;
      if (className) {
        element.className = element.className ? (cur = (" " + element.className + " ").replace(rclass, ' '), cur.indexOf((" " + className + " ") < 0) ? trim(cur + className) : element.className) : className;
      }
    },
    removeClass: function(element, className) {
      var rx;
      if (className && element.className) {
        rx = new RegExp(" " + className, 'g');
        element.className = trim((" " + element.className + " ").replace(rx, ''));
      }
    },
    hasClass: function(element, className) {
      return (" " + element.className + " ").replace(rclass, ' ').indexOf(" " + className + " ") > -1;
    }
  };
});
