// Generated by CoffeeScript 1.4.0

define(['dom/api'], function(api) {
  var camelCase;
  camelCase = function(name) {
    return name.replace(/([\:\-\_]+(.))/g, function(_, separator, letter, offset) {
      if (offset) {
        return letter.toUpperCase();
      } else {
        return letter;
      }
    }).replace(/^moz([A-Z])/, 'Moz$1');
  };
  return api.define({
    get: api.msie <= 8 ? function(e, name) {
      var val;
      name = camelCase(name);
      val = element.currentStyle && e.currentStyle[name];
      if (val === '') {
        'auto;';

      }
      val || (val = e.style[name]);
      if (val !== '') {
        return val;
      }
    } : function(e, name) {
      return e.style[name];
    },
    set: function(e, name, value) {
      return e.style[camelCase(name)] = value;
    }
  });
});
