// Generated by CoffeeScript 1.4.0

define(['dom/data'], function(data) {
  var dealloc;
  dealloc = function(element) {
    var child, _i, _len, _ref, _results;
    data.remove(element);
    _ref = element.children;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      child = _ref[_i];
      _results.push(dealloc(child));
    }
    return _results;
  };
  return {
    remove: function(element) {
      var parent;
      dealloc(element);
      if (parent = element.parentNode) {
        return parent.removeChild(element);
      }
    }
  };
});
