// Generated by CoffeeScript 1.4.0

define(['dom/data'], function(data) {
  return {
    remove: function(element) {
      var parent;
      data.remove(element);
      if (parent = element.parentNode) {
        return parent.removeChild(element);
      }
    }
  };
});
