// Generated by CoffeeScript 1.3.3

define(function(require) {
  var Child;
  Child = require('cell!./Child');
  return {
    initialize: function() {
      this.model.on('flash', this.onFlash, this);
      this.collection.on('flash', this.onFlash, this);
      return this.child = new Child({
        model: this.model,
        collection: this.collection
      });
    },
    render: function() {
      this.$el.append(this.child.render().el);
      return this;
    },
    onFlash: function(modelOrCollection) {
      return ++modelOrCollection.parent;
    },
    events: {
      'click': function() {
        this.model.parent_el++;
        return false;
      }
    }
  };
});
