// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Child;

  Child = require('./Child');
  return require('cell/defineView!')({
    initialize: function() {
      this.listenTo(this.model, 'flash', this.onFlash);
      this.listenTo(this.collection, 'flash', this.onFlash);
      return this.child = new Child({
        model: this.model,
        collection: this.collection
      });
    },
    render: function() {
      this.$el.append(this.child.render().el);
      return this;
    },
    onFlash: function(modelOrCollection) {
      return ++modelOrCollection.parent;
    },
    events: {
      'click': function() {
        this.model.parent_el++;
        return false;
      }
    }
  });
});

/*
//@ sourceMappingURL=Parent.map
*/
