// Generated by CoffeeScript 1.3.3

define(function(require) {
  var Parent;
  Parent = require('cell!./Parent');
  return {
    initialize: function() {
      this.model.on('flash', this.onFlash, this);
      this.collection.on('flash', this.onFlash, this);
      return this.parent = new Parent({
        model: this.model,
        collection: this.collection
      });
    },
    render: function() {
      this.$el.append(this.parent.render().el);
      return this;
    },
    onFlash: function(modelOrCollection) {
      return ++modelOrCollection.root;
    },
    events: {
      'click': function() {
        this.model.root_el++;
        return false;
      }
    }
  };
});
