/*!
 Lo-Dash 1.0.0-rc.3 (Custom Build) lodash.com/license
 Build: `lodash backbone -o support/lodash.custom.js`
 Underscore.js 1.4.3 underscorejs.org/LICENSE
*/
;(function(e,t){function s(e){if(e&&"object"==typeof e&&e.__wrapped__)return e;if(!(this instanceof s))return new s(e);this.__wrapped__=e}function o(e){var t=e.length,n=20<=t-1;if(n)for(var r={},i=0;++i<t;){var s=e[i]+"";(Y.call(r,s)?r[s]:r[s]=[]).push(e[i])}return function(t){if(n){var i=t+"";return Y.call(r,i)&&-1<H(r[i],t)}return-1<H(e,t,1)}}function u(e){return e.charCodeAt(0)}function a(e,t){var n=e.b,r=t.b,e=e.a,t=t.a;if(e!==t){if(e>t||"undefined"==typeof e)return 1;if(e<t||"undefined"==typeof 
t)return-1}return n<r?-1:1}function f(e,t,n){function i(){var a=arguments,f=o?this:t;return s||(e=t[u]),n.length&&(a=a.length?n.concat(v(a)):n),this instanceof i?(d.prototype=e.prototype,f=new d,d.prototype=r,a=e.apply(f,a),S(a)?a:f):e.apply(f,a)}var s=E(e),o=!n,u=t;return o&&(n=t),s||(t=e),i}function l(e,t,n){return e?"function"!=typeof e?function(t){return t[e]}:"undefined"!=typeof t?n?function(n,r,i,s){return e.call(t,n,r,i,s)}:function(n,r,i){return e.call(t,n,r,i)}:e:I}function c(){for(var e=
{b:"",c:"",e:yt,f:gt,g:"",h:wt,i:xt,j:K,k:"",l:n},t,r=0;t=arguments[r];r++)for(var i in t)e[i]=t[i];t=e.a,e.d=/^[^,]+/.exec(t)[0],r="var i,l="+e.d+",t="+e.d+";if(!"+e.d+")return t;"+e.k+";",e.b?(r+="var m=l.length;i=-1;if(typeof m=='number'){",e.i&&(r+="if(k(l)){l=l.split('')}"),r+="while(++i<m){"+e.b+"}}else {"):e.h&&(r+="var m=l.length;i=-1;if(m&&j(l)){while(++i<m){i+='';"+e.g+"}}else {"),e.e||(r+="var u=typeof l=='function'&&s.call(l,'prototype');");if(e.f&&e.l)r+="var q=-1,r=p[typeof l]?n(l):[],m=r.length;while(++q<m){i=r[q];"
,e.e||(r+="if(!(u&&i=='prototype')){"),r+=e.g+"",e.e||(r+="}");else{r+="for(i in l){";if(!e.e||e.l)r+="if(",e.e||(r+="!(u&&i=='prototype')"),!e.e&&e.l&&(r+="&&"),e.l&&(r+="h.call(l,i)"),r+="){";r+=e.g+";";if(!e.e||e.l)r+="}"}r+="}";if(e.e){r+="var f=l.constructor;";for(i=0;7>i;i++)r+="i='"+e.j[i]+"';if(","constructor"==e.j[i]&&(r+="!(f&&f.prototype===l)&&"),r+="h.call(l,i)){"+e.g+"}"}if(e.b||e.h)r+="}";return r+=e.c+";return t",Function("e,h,j,k,p,n,s","return function("+t+"){"+r+"}")(l,Y,m,x,Lt,
it,et)}function h(e){return Pt[e]}function p(e){return"function"!=typeof e.toString&&"string"==typeof (e+"")}function d(){}function v(e,t,n){t||(t=0),"undefined"==typeof n&&(n=e?e.length:0);for(var r=-1,n=n-t||0,i=Array(0>n?0:n);++r<n;)i[r]=e[t+r];return i}function m(e){return tt.call(e)==at}function g(e){var t=[];return Dt(e,function(e,n){t.push(n)}),t}function y(e,t,n,s,o){if(e==r)return e;n&&(t=i);if(n=S(e)){var u=tt.call(e);if(!Ct[u]||Tt&&p(e))return e;var a=Ht(e)}if(!n||!t)return n?a?v(e):Mt
({},e):e;n=kt[u];switch(u){case lt:case ct:return new n(+e);case ht:case vt:return new n(e);case dt:return n(e.source,V.exec(e))}s||(s=[]),o||(o=[]);for(u=s.length;u--;)if(s[u]==e)return o[u];var f=a?n(e.length):{};return s.push(e),o.push(f),(a?A:Dt)(e,function(e,n){f[n]=y(e,t,r,s,o)}),a&&(Y.call(e,"index")&&(f.index=e.index),Y.call(e,"input")&&(f.input=e.input)),f}function b(e){var t=[];return _t(e,function(e,n){E(e)&&t.push(n)}),t.sort()}function w(e,t,s,o){if(e===t)return 0!==e||1/e==1/t;if(e==
r||t==r)return e===t;var u=tt.call(e),a=tt.call(t);u==at&&(u=pt),a==at&&(a=pt);if(u!=a)return i;switch(u){case lt:case ct:return+e==+t;case ht:return e!=+e?t!=+t:0==e?1/e==1/t:e==+t;case dt:case vt:return e==t+""}a=u==ft;if(!a){if(e.__wrapped__||t.__wrapped__)return w(e.__wrapped__||e,t.__wrapped__||t);if(u!=pt||Tt&&(p(e)||p(t)))return i;var u=!Et&&m(e)?Object:e.constructor,f=!Et&&m(t)?Object:t.constructor;if(u!=f&&(!E(u)||!(u instanceof u&&E(f)&&f instanceof f)))return i}s||(s=[]),o||(o=[]);for(
u=s.length;u--;)if(s[u]==e)return o[u]==t;var l=n,c=0;s.push(e),o.push(t);if(a){c=e.length;if(l=c==t.length)for(;c--&&(l=w(e[c],t[c],s,o)););return l}return _t(e,function(e,n,r){if(Y.call(r,n))return c++,l=Y.call(t,n)&&w(e,t[n],s,o)}),l&&_t(t,function(e,t,n){if(Y.call(n,t))return l=-1<--c}),l}function E(e){return"function"==typeof e}function S(e){return e?Lt[typeof e]:i}function x(e){return"string"==typeof e||tt.call(e)==vt}function T(e){var t=[];return Dt(e,function(e){t.push(e)}),t}function N(e
,t,n){var r=-1,s=e?e.length:0,o=i,n=(0>n?st(0,s+n):n)||0;return"number"==typeof s?o=-1<(x(e)?e.indexOf(t,n):H(e,t,n)):Ot(e,function(e){if(++r>=n)return!(o=e===t)}),o}function C(e,t,r){var i=n,t=l(t,r);if(Ht(e))for(var r=-1,s=e.length;++r<s&&(i=!!t(e[r],r,e)););else Ot(e,function(e,n,r){return i=!!t(e,n,r)});return i}function k(e,t,n){var r=[],t=l(t,n);if(Ht(e))for(var n=-1,i=e.length;++n<i;){var s=e[n];t(s,n,e)&&r.push(s)}else Ot(e,function(e,n,i){t(e,n,i)&&r.push(e)});return r}function L(e,t,n){
var r,t=l(t,n);return A(e,function(e,n,s){if(t(e,n,s))return r=e,i}),r}function A(e,t,n){if(Ht(e)){var r=-1,s=e.length;if(!t||"undefined"!=typeof n)t=l(t,n);for(;++r<s&&t(e[r],r,e)!==i;);}else Ot(e,t,n);return e}function O(e,t,n){var r=-1,i=e?e.length:0,s=Array("number"==typeof i?i:0),t=l(t,n);if(Ht(e))for(;++r<i;)s[r]=t(e[r],r,e);else Ot(e,function(e,n,i){s[++r]=t(e,n,i)});return s}function M(e,t,n,r){var s=3>arguments.length,t=l(t,r,X);if(Ht(e)){var o=-1,u=e.length;for(s&&(n=e[++o]);++o<u;)n=t(
n,e[o],o,e)}else Ot(e,function(e,r,o){n=s?(s=i,e):t(n,e,r,o)});return n}function _(e,t,n,r){var s=e,o=e?e.length:0,u=3>arguments.length;if("number"!=typeof o)var a=Bt(e),o=a.length;else xt&&x(e)&&(s=e.split(""));return t=l(t,r,X),A(e,function(e,r,f){r=a?a[--o]:--o,n=u?(u=i,s[r]):t(n,s[r],r,f)}),n}function D(e,t,n){var r,t=l(t,n);if(Ht(e))for(var n=-1,i=e.length;++n<i&&!(r=t(e[n],n,e)););else Ot(e,function(e,n,i){return!(r=t(e,n,i))});return!!r}function P(e,t,n){if(e){var i=e.length;return t==r||n?
e[0]:v(e,0,ot(st(0,t),i))}}function H(e,t,n){var r=-1,i=e?e.length:0;if("number"==typeof n)r=(0>n?st(0,i+n):n||0)-1;else if(n)return r=j(e,t),e[r]===t?r:-1;for(;++r<i;)if(e[r]===t)return r;return-1}function B(e,t,n){return v(e,t==r||n?1:st(0,t))}function j(e,t,n,r){for(var i=0,s=e?e.length:i,n=n?l(n,r):I,t=n(t);i<s;)r=i+s>>>1,n(e[r])<t?i=r+1:s=r;return i}function F(e,t){return mt||nt&&2<arguments.length?nt.call.apply(nt,arguments):f(e,t,v(arguments,2))}function I(e){return e}function q(e){A(b(e),
function(t){var r=s[t]=e[t];s.prototype[t]=function(){var e=[this.__wrapped__];return Z.apply(e,arguments),e=r.apply(s,e),this.__chain__&&(e=new s(e),e.__chain__=n),e}})}var n=!0,r=null,i=!1,R="object"==typeof exports&&exports,U="object"==typeof global&&global;U.global===U&&(e=U);var z=[],U=new function(){},W=0,X=U,V=/\w*$/,$=RegExp("^"+(U.valueOf+"").replace(/[.*+?^=!:${}()|[\]\/\\]/g,"\\$&").replace(/valueOf|for [^\]]+/g,".+?")+"$"),J=/[&<>"']/g,K="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf"
.split(" "),Q=z.concat,G=Math.floor,Y=U.hasOwnProperty,Z=z.push,et=U.propertyIsEnumerable,tt=U.toString,nt=$.test(nt=v.bind)&&nt,rt=$.test(rt=Array.isArray)&&rt,it=$.test(it=Object.keys)&&it,st=Math.max,ot=Math.min,ut=Math.random,at="[object Arguments]",ft="[object Array]",lt="[object Boolean]",ct="[object Date]",ht="[object Number]",pt="[object Object]",dt="[object RegExp]",vt="[object String]",U=!!e.attachEvent,$=nt&&!/\n|true/.test(nt+U),mt=nt&&!$,gt=it&&(U||$),yt,bt=(bt={0:1,length:1},z.splice
.call(bt,0,1),bt[0]),wt=n;(function(){function e(){this.x=1}var t=[];e.prototype={valueOf:1,y:1};for(var n in new e)t.push(n);for(n in arguments)wt=!n;yt=!/valueOf/.test(t)})(1);var Et=arguments.constructor==Object,St=!m(arguments),xt="xx"!="x"[0]+Object("x")[0];try{var Tt=("[object Object]",tt.call(document)==pt)}catch(Nt){}var Ct={"[object Function]":i};Ct[at]=Ct[ft]=Ct[lt]=Ct[ct]=Ct[ht]=Ct[pt]=Ct[dt]=Ct[vt]=n;var kt={};kt[ft]=Array,kt[lt]=Boolean,kt[ct]=Date,kt[pt]=Object,kt[ht]=Number,kt[dt]=
RegExp,kt[vt]=String;var Lt={"boolean":i,"function":n,object:n,number:i,string:i,"undefined":i},U={a:"o,v,g",k:"for(var a=1,b=typeof g=='number'?2:arguments.length;a<b;a++){if((l=arguments[a])){",g:"t[i]=l[i]",c:"}}"},$={a:"d,c,w",k:"c=c&&typeof w=='undefined'?c:e(c,w)",b:"if(c(l[i],i,d)===false)return t",g:"if(c(l[i],i,d)===false)return t"},At={b:r},Ot=c($),Mt=c(U);St&&(m=function(e){return e?Y.call(e,"callee"):i});var _t=c($,At,{l:i}),Dt=c($,At),Pt={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"
,"'":"&#x27;"},U=c(U,{g:"if(t[i]==null)"+U.g}),Ht=rt||function(e){return Et&&e instanceof Array||tt.call(e)==ft};E(/x/)&&(E=function(e){return e instanceof Function||"[object Function]"==tt.call(e)});var Bt=it?function(e){return"function"==typeof e&&et.call(e,"prototype")?g(e):S(e)?it(e):[]}:g;s.assign=Mt,s.bind=F,s.bindAll=function(e){for(var t=arguments,n=1<t.length?0:(t=b(e),-1),r=t.length;++n<r;){var i=t[n];e[i]=F(e[i],e)}return e},s.countBy=function(e,t,n){var r={},t=l(t,n);return A(e,function(
e,n,i){n=t(e,n,i),Y.call(r,n)?r[n]++:r[n]=1}),r},s.defaults=U,s.filter=k,s.forEach=A,s.forIn=_t,s.forOwn=Dt,s.functions=b,s.groupBy=function(e,t,n){var r={},t=l(t,n);return A(e,function(e,n,i){n=t(e,n,i),(Y.call(r,n)?r[n]:r[n]=[]).push(e)}),r},s.initial=function(e,t,n){if(!e)return[];var i=e.length;return v(e,0,ot(st(0,i-(t==r||n?1:t||0)),i))},s.invoke=function(e,t){var n=v(arguments,2),r="function"==typeof t,i=[];return A(e,function(e){i.push((r?t:e[t]).apply(e,n))}),i},s.keys=Bt,s.map=O,s.max=function(
e,t,n){var r=-Infinity,i=-1,s=e?e.length:0,o=r;if(t||!Ht(e))t=!t&&x(e)?u:l(t,n),Ot(e,function(e,n,i){n=t(e,n,i),n>r&&(r=n,o=e)});else for(;++i<s;)e[i]>o&&(o=e[i]);return o},s.min=function(e,t,n){var r=Infinity,i=-1,s=e?e.length:0,o=r;if(t||!Ht(e))t=!t&&x(e)?u:l(t,n),Ot(e,function(e,n,i){n=t(e,n,i),n<r&&(r=n,o=e)});else for(;++i<s;)e[i]<o&&(o=e[i]);return o},s.once=function(e){var t,s=i;return function(){return s?t:(s=n,t=e.apply(this,arguments),e=r,t)}},s.pick=function(e,t,n){var r={};if("function"!=typeof 
t)for(var i=0,s=Q.apply(z,arguments),o=s.length;++i<o;){var u=s[i];u in e&&(r[u]=e[u])}else t=l(t,n),_t(e,function(e,n,i){t(e,n,i)&&(r[n]=e)});return r},s.reject=function(e,t,n){return t=l(t,n),k(e,function(e,n,r){return!t(e,n,r)})},s.rest=B,s.shuffle=function(e){var t=-1,n=Array(e?e.length:0);return A(e,function(e){var r=G(ut()*(++t+1));n[t]=n[r],n[r]=e}),n},s.sortBy=function(e,t,n){var r=[],t=l(t,n);A(e,function(e,n,i){r.push({a:t(e,n,i),b:n,c:e})}),e=r.length;for(r.sort(a);e--;)r[e]=r[e].c;return r
},s.toArray=function(e){return"number"==typeof (e?e.length:0)?xt&&x(e)?e.split(""):v(e):T(e)},s.values=T,s.without=function(e){for(var t=-1,n=e?e.length:0,r=o(arguments),i=[];++t<n;){var s=e[t];r(s)||i.push(s)}return i},s.collect=O,s.drop=B,s.each=A,s.extend=Mt,s.methods=b,s.select=k,s.tail=B,s.clone=y,s.contains=N,s.escape=function(e){return e==r?"":(e+"").replace(J,h)},s.every=C,s.find=L,s.has=function(e,t){return e?Y.call(e,t):i},s.identity=I,s.indexOf=H,s.isArguments=m,s.isArray=Ht,s.isEmpty=
function(e){var t=n;if(!e)return t;var r=tt.call(e),s=e.length;return r==ft||r==vt||r==at||St&&m(e)||r==pt&&"number"==typeof s&&E(e.splice)?!s:(Dt(e,function(){return t=i}),t)},s.isEqual=w,s.isFunction=E,s.isObject=S,s.isRegExp=function(e){return e instanceof RegExp||tt.call(e)==dt},s.isString=x,s.lastIndexOf=function(e,t,n){var r=e?e.length:0;for("number"==typeof n&&(r=(0>n?st(0,r+n):ot(n,r-1))+1);r--;)if(e[r]===t)return r;return-1},s.mixin=q,s.reduce=M,s.reduceRight=_,s.result=function(e,t){var n=
e?e[t]:r;return E(n)?e[t]():n},s.size=function(e){var t=e?e.length:0;return"number"==typeof t?t:Bt(e).length},s.some=D,s.sortedIndex=j,s.uniqueId=function(e){return(e==r?"":e+"")+ ++W},s.all=C,s.any=D,s.detect=L,s.foldl=M,s.foldr=_,s.include=N,s.inject=M,s.first=P,s.last=function(e,t,n){if(e){var i=e.length;return t==r||n?e[i-1]:v(e,st(0,i-t))}},s.take=P,s.head=P,s.chain=function(e){return e=new s(e),e.__chain__=n,e},s.VERSION="1.0.0-rc.3",q(s),s.prototype.chain=function(){return this.__chain__=n
,this},s.prototype.value=function(){return this.__wrapped__},Ot("pop push reverse shift sort splice unshift".split(" "),function(e){var t=z[e];s.prototype[e]=function(){var e=this.__wrapped__;return t.apply(e,arguments),bt&&e.length===0&&delete e[0],this}}),Ot(["concat","join","slice"],function(e){var t=z[e];s.prototype[e]=function(){var e=t.apply(this.__wrapped__,arguments);return this.__chain__&&(e=new s(e),e.__chain__=n),e}}),typeof define=="function"&&typeof define.amd=="object"&&define.amd?(
e._=s,define(function(){return s})):R?"object"==typeof module&&module&&module.exports==R?(module.exports=s)._=s:R._=s:e._=s})(this);