// Generated by CoffeeScript 1.4.0

define(['cell/Ext', 'dom/class'], function(Ext, _arg) {
  var addClass, removeClass;
  addClass = _arg.addClass, removeClass = _arg.removeClass;
  return Ext.extend(function(element, classHash, getValue) {
    var k, v, _fn;
    if (!(classHash && classHash.constructor === Object)) {
      return;
    }
    _fn = function(k) {
      return getValue(v, function(value) {
        return (value ? addClass : removeClass)(element, k);
      });
    };
    for (k in classHash) {
      v = classHash[k];
      _fn(k);
    }
  });
});
