// Generated by CoffeeScript 1.6.1

define(['cell/Ext', 'util/fn', 'util/type', 'dom/class'], function(Ext, fn, type, cls) {
  return Ext.extend({
    render: function() {
      var k, opts, v, _fn,
        _this = this;
      opts = this.options;
      if (opts && opts.constructor === Object) {
        _fn = function(k) {
          _this.watch((type.isF(v) ? fn.b0(v, _this.view) : v), function(value) {
            (value ? cls.add : cls.remove)(this.el, k);
          });
        };
        for (k in opts) {
          v = opts[k];
          _fn(k);
        }
      }
    }
  });
});
