// Generated by CoffeeScript 1.4.0

define(['utils', 'dom/events', 'cell/Ext'], function(utils, events, Ext) {
  var ModelElement, getModelValue, onElementChange;
  ModelElement = {
    text: {
      g: 'value',
      s: function(value) {
        this.el[this.ea] = value;
      }
    },
    checkbox: {
      g: 'checked',
      s: function(value) {
        this.el[this.ea] = !!value;
      }
    }
  };
  onElementChange = function() {
    this.m[this.ma] = this.el[this.ea];
    this.v.updateBinds();
  };
  getModelValue = function() {
    return this.m[this.ma];
  };
  return Ext.extend({
    func: function(el, ma, getValue, v) {
      var modelEl;
      this.el = el;
      this.ma = ma;
      this.v = v;
      if ((this.el.tagName === 'INPUT') && (modelEl = ModelElement[this.el.type.toLowerCase()])) {
        this.m = this.v.model;
        this.ea = modelEl.g;
        events.bind(this.el, 'change', utils.bind(onElementChange, this));
        getValue(utils.bind(getModelValue, this), utils.bind(modelEl.s, this));
      }
    }
  });
});
