// Generated by CoffeeScript 1.4.0

define(['dom/events', 'cell/Ext'], function(events, Ext) {
  var ModelElement, text;
  ModelElement = {
    input: {
      text: text = {
        e: 'keyup',
        g: 'value',
        s: function(value) {
          this.el[this.ea] = value;
        }
      },
      checkbox: {
        e: 'change',
        g: 'checked',
        s: function(value) {
          this.el[this.ea] = !!value;
        }
      }
    },
    select: {
      e: 'change',
      g: text.g,
      s: text.s
    },
    textarea: text
  };
  return Ext.extend({
    func: function(el, ma, getValue, view) {
      var modelEl, tag;
      this.el = el;
      if (modelEl = ModelElement[tag = el.tagName.toLowerCase()]) {
        if (tag === 'input') {
          modelEl = modelEl[el.type];
        }
      }
      if (modelEl) {
        this.ea = modelEl.g;
        events.on(el, modelEl.e, function() {
          view.model.set(ma, el[modelEl.g]);
        });
        getValue((function() {
          return this.model.get(ma);
        }), modelEl.s);
      }
    }
  });
});
