// Generated by CoffeeScript 1.4.0

define(function() {
  return function(proto) {
    var Child, Parent, Surrogate, k;
    Parent = this;
    Child = function(options) {
      if (!(this instanceof Child)) {
        return new Child(options);
      }
      Parent.call(this, options);
      if (proto && proto.constructor) {
        proto.constructor.call(this, options);
      }
    };
    Child.extend = Parent.extend;
    Surrogate = function() {};
    Surrogate.prototype = Parent.prototype;
    Child.prototype = new Surrogate();
    if (proto) {
      for (k in proto) {
        Child.prototype[k] = proto[k];
      }
      if (proto.constructor) {
        Child.prototype.constructor = proto.constructor;
      }
    }
    return Child;
  };
});
