// Generated by CoffeeScript 1.6.1

define({
  b: function(f, o) {
    return function() {
      return f.apply(o, arguments);
    };
  },
  b0: function(f, o) {
    return function() {
      return f.call(o);
    };
  },
  b1: function(f, o) {
    return function(a1) {
      return f.call(o, a1);
    };
  },
  b2: function(f, o) {
    return function(a1, a2) {
      return f.call(o, a1, a2);
    };
  }
});
