// Generated by CoffeeScript 1.6.3
define(function() {
  var hashuid;
  hashuid = 0;
  return function(obj) {
    var objType;
    if (((objType = typeof obj) === 'object') && obj !== null) {
      return obj.$$hashkey || (obj.$$hashkey = "" + (++hashuid));
    } else {
      return objType + ':' + obj;
    }
  };
});

/*
//@ sourceMappingURL=hash.map
*/
