// Generated by CoffeeScript 1.6.1

define({
  isA: Array.isArray || function(o) {
    return o instanceof Array;
  },
  isS: function(o) {
    return typeof o === 'string';
  },
  isF: function(o) {
    return typeof o === 'function';
  }
});
