// Generated by CoffeeScript 1.4.0

define(function() {
  var Ext, Surrogate;
  Surrogate = function() {};
  Ext = function() {};
  Ext.prototype.getValue = function(v, callback) {
    return callback(typeof v === 'function' ? v() : v);
  };
  Ext.prototype.run = function(element) {
    this.func(element, this.options, this.getValue);
  };
  Ext.extend = function(func) {
    var NewExt;
    NewExt = function(options) {
      if (!(this instanceof NewExt)) {
        return new NewExt(options);
      }
      this.options = options;
    };
    Surrogate.prototype = Ext.prototype;
    NewExt.prototype = new Surrogate();
    NewExt.prototype.func = func;
    return NewExt;
  };
  return Ext;
});
