// Generated by CoffeeScript 1.4.0

define(['util/type', 'util/fn', 'util/extend', 'cell/util/spy'], function(type, fn, extend, spy) {
  var Ext;
  Ext = function(options) {
    this.options = options != null ? options : {};
    this.getValue = fn.bind(this.getValue, this);
  };
  Ext.prototype = {
    getValue: function(v, callback) {
      var _this = this;
      if (type.isF(v)) {
        spy.watch(fn.bind(v, this.view), function(value) {
          callback.call(_this, value);
        });
      } else {
        callback.call(this, v);
      }
    },
    run: function(element, view) {
      this.view = view;
      this.func(element, this.options, this.getValue, this.view);
    }
  };
  Ext.extend = extend;
  return Ext;
});
