// Generated by CoffeeScript 1.6.2
define(['util/extend', 'cell/util/spy'], function(extend, spy) {
  var Ext;

  Ext = function(options) {
    this.options = options != null ? options : {};
  };
  Ext.prototype.watch = function(v, callback) {
    spy.watch(this.view, v, callback, this);
  };
  Ext.prototype.run = function(element, view) {
    this.view = view;
    this.el = element;
    this.render();
  };
  Ext.extend = extend;
  return Ext;
});

/*
//@ sourceMappingURL=Ext.map
*/
