// Generated by CoffeeScript 1.4.0

define(['util/type', 'cell/Events', 'cell/util/spy'], function(type, Events, spy) {
  var Model;
  Model = Events.extend({
    constructor: function(attributes) {
      this._a = attributes || {};
    },
    attributes: function() {
      var attr, result;
      this._s();
      result = {};
      for (attr in this._a) {
        result[attr] = this._a[attr];
      }
      return result;
    },
    get: function(key) {
      this._s(key);
      return this._a[key];
    },
    set: function(key, value) {
      var old_value;
      if ((type.isS(key)) && (this._a[key] !== value)) {
        old_value = this._a[key];
        this.trigger("change:" + key, this, (this._a[key] = value), old_value);
        return true;
      }
    },
    onChangeAndDo: function(key, cb, ctx) {
      if (this.on("change:" + key, cb, ctx)) {
        cb("initial:" + key, this, this.get(key));
      }
    },
    _s: spy.addModel
  });
  return Model;
});
