// Generated by CoffeeScript 1.6.1

define(['cell/Events'], function(Events) {
  return Events.extend({
    constructor: function(o) {},
    run: function(input) {
      return input;
    }
  });
});
