// Generated by CoffeeScript 1.4.0

define(function(require) {
  var MockNested;
  MockNested = require('dir/MockNested');
  return require('cell/defineView!')({
    renderEl: function(__) {
      return ["Mock: ", __(MockNested)];
    }
  });
});
