// Generated by CoffeeScript 1.3.1
(function() {
  var nodeHTMLEquals, nodeToHTML;

  define({
    nodeHTMLEquals: nodeHTMLEquals = function(node, expectedHTML) {
      ok(node instanceof HTMLElement, "expected HTMLElement");
      return strictEqual(nodeToHTML(node), expectedHTML, "expected " + expectedHTML);
    },
    nodeToHTML: nodeToHTML = function(node) {
      var attr, child, html, list, name, value, _i, _j, _len, _len1, _ref, _ref1;
      if (node.tagName) {
        html = "<" + (node.tagName.toLowerCase());
        if (node.attributes.length > 0) {
          list = (function() {
            var _i, _len, _ref, _results;
            _ref = node.attributes;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              attr = _ref[_i];
              _results.push(attr);
            }
            return _results;
          })();
          list.sort(function(a, b) {
            if (a.name === b.name) {
              return 0;
            } else if (a.name < b.name) {
              return -1;
            } else {
              return 1;
            }
          });
          for (_i = 0, _len = list.length; _i < _len; _i++) {
            _ref = list[_i], name = _ref.name, value = _ref.value;
            html += " " + name + "=\"" + value + "\"";
          }
        }
        html += ">";
        _ref1 = $(node).contents();
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          child = _ref1[_j];
          html += nodeToHTML(child);
        }
        return html += "</" + (node.tagName.toLowerCase()) + ">";
      } else {
        return $(node).text();
      }
    }
  });

}).call(this);
