// Generated by CoffeeScript 1.6.2
define(function() {
  return function(_arg) {
    var beforeEachRequire;

    beforeEachRequire = _arg.beforeEachRequire;
  };
});

/*
//@ sourceMappingURL=Backbone.spec.map
*/
