// Generated by CoffeeScript 1.6.2
var __slice = [].slice;

define(['../../utils/spec-utils'], function(_arg) {
  var node;

  node = _arg.node;
  return function(_arg1) {
    var beforeEachRequire;

    beforeEachRequire = _arg1.beforeEachRequire;
    beforeEachRequire(['cell/Ext', 'cell/View', 'require'], function(Ext, View, require) {
      this.Ext = Ext;
      this.View = View;
      this.require = require;
    });
    return describe('modifies View._() method signature ( viewOrSelector:[View, String], exts...:Ext, attrHash_or_options?:Object, children...:[DOMElement, String, Number, Array, jQuery] )', function() {
      beforeEach(function() {
        this.x_test1 = this.Ext.extend({
          render: this.x_test1_func = jasmine.createSpy('x_test1_func')
        });
        this.x_test2 = this.Ext.extend({
          render: this.x_test2_func = jasmine.createSpy('x_test2_func')
        });
        this.view = new this.View;
        return this._ = this.view._;
      });
      describe('_( selector:String, exts...:Ext )', function() {
        beforeEach(function() {
          return this.result = this._('.myClass', this.x_test1_instance = this.x_test1(this.x_test1_options = {}), this.x_test2_instance = this.x_test2(this.x_test2_options = {}));
        });
        return it('calls Ext.run(element) for each ext', function() {
          expect(this.x_test1_func).toHaveBeenCalledWith();
          expect(this.x_test1_func.callCount).toBe(1);
          expect(this.x_test2_func).toHaveBeenCalledWith();
          return expect(this.x_test2_func.callCount).toBe(1);
        });
      });
      describe('_( selector:String, exts...:Ext, attrHash_or_options:Object )', function() {
        beforeEach(function() {
          return this.result = this._('.myClass', this.x_test1_instance = this.x_test1(this.x_test1_options = {}), this.x_test2_instance = this.x_test2(this.x_test2_options = {}), this.options = {
            a: 1
          });
        });
        return it('calls Ext.run(element) for each ext', function() {
          expect(this.x_test1_func).toHaveBeenCalledWith();
          expect(this.x_test1_func.callCount).toBe(1);
          expect(this.x_test2_func).toHaveBeenCalledWith();
          return expect(this.x_test2_func.callCount).toBe(1);
        });
      });
      describe('_( selector:String, exts...:Ext, attrHash_or_options:Object, children...:[DOMElement, String, Number, Array] )', function() {
        beforeEach(function() {
          return this.result = this._.apply(this, [(this.sel_arg = '.myClass'), this.x_test1_instance = this.x_test1(this.x_test1_options = {}), this.x_test2_instance = this.x_test2(this.x_test2_options = {}), this.options = {
            a: 1
          }].concat(__slice.call((this.child_args = [node('a'), 'hello', 0, [node('b'), 'bye', 1]]))));
        });
        return it('calls Ext.run(element) for each ext', function() {
          expect(this.x_test1_func).toHaveBeenCalledWith();
          expect(this.x_test1_func.callCount).toBe(1);
          expect(this.x_test2_func).toHaveBeenCalledWith();
          return expect(this.x_test2_func.callCount).toBe(1);
        });
      });
      return describe('_( selector:String, exts...:Ext, children...:[DOMElement, String, Number, Array] )', function() {
        beforeEach(function() {
          return this.result = this._.apply(this, [(this.sel_arg = '.myClass'), this.x_test1_instance = this.x_test1(this.x_test1_options = {}), this.x_test2_instance = this.x_test2(this.x_test2_options = {})].concat(__slice.call((this.child_args = [node('a'), 'hello', 0, [node('b'), 'bye', 1]]))));
        });
        return it('calls Ext.run(element) for each ext', function() {
          expect(this.x_test1_func).toHaveBeenCalledWith();
          expect(this.x_test1_func.callCount).toBe(1);
          expect(this.x_test2_func).toHaveBeenCalledWith();
          return expect(this.x_test2_func.callCount).toBe(1);
        });
      });
    });
  };
});

/*
//@ sourceMappingURL=ViewExts.spec.map
*/
