// Generated by CoffeeScript 1.4.0

define(function() {
  return function(_arg) {
    var beforeEachRequire;
    beforeEachRequire = _arg.beforeEachRequire;
    beforeEachRequire(['cell/Ext', 'cell/View', 'require'], function(Ext, View, require) {
      this.Ext = Ext;
      this.View = View;
      this.require = require;
    });
    return describe('modifies View.__() method signature ( viewOrSelector:[Backbone.View, String], exts...:Ext, attrHash_or_options?:Object, children...:[DOMNode, String, Number, Array, jQuery] )', function() {
      beforeEach(function() {
        var _this = this;
        this.orig__ = (spyOn(this.View.prototype, '__')).andReturn(this.element = {});
        this.x_test1 = this.Ext.extend(this.x_test1_func = jasmine.createSpy('x_test1_func'));
        this.x_test2 = this.Ext.extend(this.x_test2_func = jasmine.createSpy('x_test2_func'));
        runs(function() {
          return _this.require(['cell/opts/ViewExts'], function(ViewExts) {
            _this.ViewExts = ViewExts;
          });
        });
        waitsFor(function() {
          return _this.ViewExts;
        });
        return runs(function() {
          _this.view = new _this.View;
          return _this.__ = _this.view.__;
        });
      });
      return describe('__( selector:String, exts...:Ext )', function() {
        beforeEach(function() {
          this.x_test1_options = {};
          this.x_test2_options = {};
          return this.result = this.__('.myClass', this.x_test1(this.x_test1_options), this.x_test2(this.x_test2_options));
        });
        it('calls Ext.run(element) for each ext', function() {
          expect(this.x_test1_func).toHaveBeenCalledWith(this.element, this.x_test1_options);
          return expect(this.x_test2_func).toHaveBeenCalledWith(this.element, this.x_test2_options);
        });
        return it('calls original View.__( selector )', function() {
          expect(this.orig__).toHaveBeenCalledWith('.myClass');
          return expect(this.result).toBe(this.element);
        });
      });
    });
  };
});
