// Generated by CoffeeScript 1.6.3
define(function(require) {
  return require('cell/defineView!')({
    render: function() {
      return ["MockNested"];
    }
  });
});

/*
//@ sourceMappingURL=MockNested.map
*/
