// Generated by CoffeeScript 1.4.0

define(function() {
  return function(_arg) {
    var beforeEachRequire;
    beforeEachRequire = _arg.beforeEachRequire;
    beforeEachRequire(['fixtures/TestCell1'], function(TestCell1) {
      this.TestCell1 = TestCell1;
      return this.testCell1 = new this.TestCell1;
    });
    return describe('@initialize()', function() {
      return it("sets cell's element with 'cell' attributes", function() {
        return expect(this.testCell1.el.getAttribute('cell')).toBe('TestCell1');
      });
    });
  };
});
