// Generated by CoffeeScript 1.6.2
define(function() {
  return function(_arg) {
    var beforeEachRequire;

    beforeEachRequire = _arg.beforeEachRequire;
    beforeEachRequire(['cell/Resource', 'cell/Collection'], function(Resource, Collection) {
      this.Resource = Resource;
      this.Collection = Collection;
    });
    describe('Resource', function() {
      describe('#create( params:object ) : ResourceInstance', function() {});
      describe('#get( params:object ) : ResourceInstance', function() {});
      return describe('#query( params:object ) : ResourceCollectionInstance', function() {});
    });
    describe('ResourceCollectionInstance', function() {
      it('is an instanceof Collection', function() {});
      return describe('@requery( params:object ) : ', function() {});
    });
    return describe('ResourceInstance', function() {
      describe('@delete( params:object ) : ResourceInstance', function() {});
      return describe('@save( params:object ) : ResourceInstance', function() {});
    });
  };
});

/*
//@ sourceMappingURL=Resource.spec.map
*/
