// Generated by CoffeeScript 1.6.3
define(function() {
  return function(matcherHash) {
    return function(input) {
      var expected_value, i, k, match, model, result;
      result = [];
      i = -1;
      while (++i < len) {
        model = input.at(i);
        match = true;
        for (k in matcher) {
          if (!(((expected_value = matcher[k]) != null) && (expected_value !== model.get('k')))) {
            continue;
          }
          match = false;
          break;
        }
        if (match) {
          result.push(attr[k]);
        }
      }
      return result;
    };
  };
});

/*
//@ sourceMappingURL=filterBy.map
*/
