// Generated by CoffeeScript 1.4.0

define(function(require) {
  var $, Backbone, Mock;
  Mock = require('./Mock');
  $ = require('jquery');
  Backbone = require('backbone');
  Backbone.$ = $;
  return $(document.body).append(new Mock().render().el);
});
