// Generated by CoffeeScript 1.3.1
(function() {

  define(['cell!./dir/MockNested'], function(MockNested) {
    return {
      render_el: function(__) {
        return ["Mock: ", __(MockNested)];
      }
    };
  });

}).call(this);
