// Generated by CoffeeScript 1.3.1
(function() {

  define(['cell!./dir/MockNested', '__'], function(MockNested, __) {
    return {
      render_el: function() {
        return ["Mock: ", __(MockNested)];
      }
    };
  });

}).call(this);
