// Generated by CoffeeScript 1.4.0

define(function() {
  return function(_arg) {
    var beforeEachRequire;
    beforeEachRequire = _arg.beforeEachRequire;
    beforeEachRequire(['cell!fixtures/TestCell1', 'cell', 'backbone'], function(TestCell1, cell, Backbone) {
      this.TestCell1 = TestCell1;
      this.cell = cell;
      this.Backbone = Backbone;
      return this.testCell1 = new this.TestCell1;
    });
    it('attaches <link> for stylesheet', function() {
      return expect($('link[href="/specs/fixtures/TestCell1.css"][rel=stylesheet][type="text/css"]').length).not.toBe(0);
    });
    it('exposes @Cell', function() {
      return expect(this.testCell1 instanceof this.cell.Cell).toBe(true);
    });
    it('Creates a Backbone.View from the definition of the module', function() {
      return expect(this.testCell1 instanceof this.Backbone.View).toBe(true);
    });
    return it('overrides Backbone.View._ensureElement() to add a cell attribute', function() {
      return expect(this.testCell1.$el.attr('cell')).toBe('TestCell1');
    });
  };
});
