// Generated by CoffeeScript 1.6.2
define(['cell/Events'], function(Events) {
  return Events.extend({
    constructor: function(o) {},
    run: function(input) {
      return input;
    }
  });
});

/*
//@ sourceMappingURL=Pipe.map
*/
