// Generated by CoffeeScript 1.4.0

define({
  isS: function(o) {
    return typeof o === 'string';
  },
  isF: function(o) {
    return typeof o === 'function';
  },
  ev: {
    rm: function(events, fn, whichOrCtx) {
      var ev, i, isWhich;
      i = -1;
      isWhich = typeof whichOrCtx === 'number';
      while (ev = events[++i]) {
        if ((isWhich ? ev[whichOrCtx] === fn : (ev[0] === fn) && (ev[1] === whichOrCtx))) {
          events.splice(i--, 1);
        }
      }
    }
  },
  bind: function(f, o) {
    return function() {
      return f.apply(o, arguments);
    };
  },
  extend: function(proto) {
    var Child, Parent, Surrogate, k;
    Parent = this;
    Child = function(options) {
      if (!(this instanceof Child)) {
        return new Child(options);
      }
      Parent.call(this, options);
    };
    Child.extend = Parent.extend;
    Surrogate = function() {};
    Surrogate.prototype = Parent.prototype;
    Child.prototype = new Surrogate();
    if (proto) {
      for (k in proto) {
        Child.prototype[k] = proto[k];
      }
    }
    return Child;
  }
});
