// Generated by CoffeeScript 1.4.0

define({
  bind: function(f, o) {
    return function() {
      return f.apply(o, arguments);
    };
  },
  extend: function(proto) {
    var Child, Parent, Surrogate, k, v;
    Parent = this;
    Child = function(options) {
      if (!(this instanceof Child)) {
        return new Child(options);
      }
      Parent.call(this, options);
    };
    Child.extend = Parent.extend;
    Surrogate = function() {};
    Surrogate.prototype = Parent.prototype;
    Child.prototype = new Surrogate();
    if (proto) {
      for (k in proto) {
        v = proto[k];
        Child.prototype[k] = v;
      }
    }
    return Child;
  }
});
