// Generated by CoffeeScript 1.3.3
(function() {

  define(['require', '../specs/GENERATED_all-specs'], function(require, specs) {
    var jasmineEnv, spec, trivialReporter, _i, _len;
    for (_i = 0, _len = specs.length; _i < _len; _i++) {
      spec = specs[_i];
      spec();
    }
    trivialReporter = new jasmine.TrivialReporter();
    jasmineEnv = jasmine.getEnv();
    jasmineEnv.updateInterval = 5000;
    jasmineEnv.addReporter(trivialReporter);
    jasmineEnv.specFilter = function(spec) {
      return trivialReporter.specFilter(spec);
    };
    return jasmineEnv.execute();
  });

}).call(this);
